### ISSUE TITLE
Doll spawn failure: wait for listener

### ISSUE THREAD

**Issue by TangleRisk** [sjavi4/PlayerDoll#32]
I'm getting the following server logs and the doll does not spawn.

The `[PlayerDoll] Wait For Listener` continues to repeat until server restart

```
[18:09:35 INFO]: TangleRisk issued server command: /playerdoll:doll spawn red
[18:09:35 INFO]: [PlayerDoll] Doll Config [-red] Saved Successfully.
[18:09:35 INFO]: [PlayerDoll] Fake Client connected to Server
[18:09:35 INFO]: [PlayerDoll] Wait For Listener
[18:09:36 INFO]: [PlayerDoll] Wait For Listener
[18:09:36 INFO]: [PlayerDoll] Wait For Listener
[18:09:36 INFO]: [PlayerDoll] Wait For Listener
```

Running purpur, here's my [mcman](https://mcman.deniz.blue/) server file which should have most versions of plugins I'm using:

```toml
name = "purpur"
mc_version = "1.20.4"

[jar]
type = "purpur"
build = "latest"

[variables]
PORT = "25565"

[launcher]
eula_args = true
nogui = true

[markdown]
files = ["README.md"]
auto_update = false

[options]
success_line = ""
stop_command = ""

[[plugins]]
type = "modrinth"
id = "simple-voice-chat"
version = "aiI5iPUK"

# https://modrinth.com/plugin/playerdoll/version/kZordHRn
[[plugins]]
type = "modrinth"
id = "playerdoll"
version = "kZordHRn"

[[plugins]]
type = "modrinth"
id = "dynmap"
version = "5F9fwzR1"

[[plugins]]
type = "curserinth"
id = "31043"
version = "5168643"

[[plugins]]
type = "curserinth"
id = "31054"
version = "4675318"

[[plugins]]
type = "hangar"
id = "Multiverse-Core"
version = "4.3.12"

[[plugins]]
type = "url"
url = "https://download.luckperms.net/1534/bukkit/loader/LuckPerms-Bukkit-5.4.121.jar"
desc = "LuckyPerms Bukkit plugin"

[[plugins]]
type = "url"
url = "https://dev.bukkit.org/projects/cleanroomgenerator/files/3596715/download"
filename = "CleanroomGenerator-1.2.1.jar"
desc = "Cleanroom Generator Plugin"

[[plugins]]
type = "ghrel"
repo = "aromaa/WorldGuardExtraFlags"
tag = "v4.2.3"
asset = "first"

[[plugins]]
type = "ghrel"
repo = "MilkBowl/Vault"
tag = "1.7.3"
asset = "first"
```

I deleted the config folder hoping that might help but it didn't. 

I've used this plugin for a while, not sure why it's having problems now.
Nothing was updated recently that might cause this change.

I'm a software engineer, it's been a few years since I coded in Java, but please let me know if I can provide more debugging info.
